import { Workbox } from 'workbox-window';

/**
 * Service Worker registration via Workbox.
 * The actual SW is generated by vite-plugin-pwa at build time.
 * In development, the SW is a no-op stub.
 */
export function registerSW(): void {
  if (typeof window === 'undefined') return;
  if (!('serviceWorker' in navigator)) {
    console.warn('Service workers are not supported in this browser');
    return;
  }

  if (import.meta.env.PROD) {
    const wb = new Workbox('/sw.js');

    wb.addEventListener('installed', (event) => {
      if (event.isUpdate) {
        // New version available — could show a toast here in Phase 5
        console.warn('New InvestPilot version available. Reload to update.');
      }
    });

    wb.addEventListener('activated', (_event) => {
      // Service worker activated — app is ready for offline use
    });

    wb.register().catch((err) => {
      console.error('Service worker registration failed:', err);
    });
  }
}
