import { Workbox } from 'workbox-window';

let _wb: Workbox | null = null;

/**
 * Service Worker registration via Workbox.
 * The actual SW is generated by vite-plugin-pwa at build time.
 * In development, the SW is a no-op stub.
 *
 * @param onUpdate  Called when a new SW version is waiting to activate.
 */
export function registerSW(onUpdate?: () => void): void {
  if (typeof window === 'undefined') return;
  if (!('serviceWorker' in navigator)) {
    console.warn('Service workers are not supported in this browser');
    return;
  }

  if (import.meta.env.PROD) {
    const wb = new Workbox('/sw.js');
    _wb = wb;

    wb.addEventListener('waiting', () => {
      onUpdate?.();
    });

    wb.addEventListener('activated', (_event) => {
      // Service worker activated — app is ready for offline use
    });

    wb.register().catch((err) => {
      console.error('Service worker registration failed:', err);
    });
  }
}

/** Tell the waiting SW to skip waiting, then reload to use the new version. */
export function applyUpdate(): void {
  if (_wb) {
    _wb.messageSkipWaiting();
  }
  window.location.reload();
}
